#ifndef _SHARED_COMMS
#define _SHARED_COMMS

#define BASE_I2C_ADDRESS 0x42

#define BASE_REGISTER_GET_STATE 0x00
#define BASE_REGISTER_SET_HDMI_A 0x01
#define BASE_REGISTER_SET_HDMI_B 0x02
#define BASE_REGISTER_SET_USB 0x03

#endif